webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from models import User


class LoginForm(FlaskForm):
    username = StringField('Имя', validators=[DataRequired()],
                           render_kw={'class': 'input100', 'placeholder': 'Имя пользователя'})
    password = PasswordField('Пароль', validators=[DataRequired()],
                             render_kw={'class': 'input100', 'placeholder': 'Пароль'})
    remember_me = BooleanField('Запомнить меня', render_kw={'class': 'checkbox mb-1'})
    submit = SubmitField('Войти', render_kw={'class': 'login100-form-btn'})


class RegistrationForm(FlaskForm):
    username = StringField('Имя', validators=[DataRequired()],
                           render_kw={'class': 'form-control', 'placeholder': 'Имя', 'style': 'border-radius:0%;'})
    email = StringField('Email', validators=[DataRequired(), Email()],
                        render_kw={'class': 'form-control', 'placeholder': 'Электронный адрес', 'style': 'border-radius:0%;'})
    password = PasswordField(
        'Пароль', validators=[DataRequired()],
        render_kw={'class': 'form-control', 'placeholder': 'Пароль', 'style': 'border-radius:0%;'})
    password2 = PasswordField(
        'Повторите пароль',
        validators=[DataRequired(), EqualTo('password', message='Пароли должны совпадать')],
        render_kw={'class': 'form-control', 'placeholder': 'Повторите пароль', 'style': 'border-radius:0%;'})
    submit = SubmitField('Отправить', render_kw={'class': 'login100-form-btn'})

    def validate_username(self, username):
        if User.query.filter_by(username=username.data).count():
            raise ValidationError('Пользователь с таким именем уже существует')

    def validate_email(self, email):
        if User.query.filter_by(email=email.data).count():
            raise ValidationError('Пользователь с таким адресом почты уже существует.')
        if email.data == '':
            raise ValidationError('Введите email-адрес')

webapp/main/views.py
from flask import Blueprint, render_template, request, url_for
from fuzzywuzzy import fuzz

from models import db, Phone, PhoneShop, Shop, normalize_name
from webapp.config import ITEMS_PER_PAGE

blueprint = Blueprint('main', __name__)


@blueprint.route('/')
@blueprint.route('/index')
def index():
    title = 'Смартфоны'
    text = request.args.get('search')
    how = request.args.get('how')
    nothing_found = True

    if text:
        if how == 'pop':
            all_phones = Phone.query.order_by(Phone.views).all()
        else:
            all_phones = Phone.query.all()
        phones = []
        for phone in all_phones:
            ratio1 = fuzz.partial_ratio(normalize_name(phone.name), text)
            ratio2 = fuzz.token_set_ratio(normalize_name(phone.name), text)
            if ratio1 + ratio2 == 200:
                phones = [phone]
                break
            if ratio1 + ratio2 > 150:
                phones.append([phone, ratio1 + ratio2])
        if len(phones) > 1:
            phones = [i[0] for i in sorted(phones, key=lambda x: x[1], reverse=True)]
        if phones:
            nothing_found = False
        return render_template('main/index.html', page_title=title, phones=get_prices(phones),
                               nothing_found=nothing_found)

    nothing_found = False
    page = request.args.get('page', 1, type=int)
    if how == 'pop':
        phones = Phone.query.order_by(Phone.views.desc()).paginate(page, ITEMS_PER_PAGE, False)
    elif how == 'price':
        phones = db.session.query(PhoneShop.phone_id, db.func.min(PhoneShop.price).label('min_price')) \
            .group_by(PhoneShop.phone_id, PhoneShop.price).order_by(PhoneShop.price.desc()) \
            .paginate(page, ITEMS_PER_PAGE, False)
    else:
        phones = Phone.query.paginate(page, ITEMS_PER_PAGE, False)
    next_url = url_for('main.index', page=phones.next_num) if phones.has_next else None
    prev_url = url_for('main.index', page=phones.prev_num) if phones.has_prev else None
    if how == 'price':
        phones_price_sorted = {}
        for item in phones.items:
            phones_price_sorted[Phone.query.filter_by(id=item.phone_id).first()] = round(item.min_price)
        phones = phones_price_sorted
    else:
        phones = get_prices(phones.items)

    return render_template('main/index.html', page_title=title, phones=phones,
                           nothing_found=nothing_found, next_url=next_url, prev_url=prev_url, how=how)


def get_prices(phones):
    """ Функция формирует словарь {телефон: минимальная_цена} для последующего вывода в шаблоне"""

    out = {}
    for phone in phones:
        prices = [round(shop.price) for shop in phone.shops if shop.price]
        out[phone] = str(min(prices)) if prices else None
    return out


@blueprint.route('/specs')
def show_specs():
    phone_id = request.args.get('phone_id', None)
    phone = Phone.query.filter_by(id=phone_id).first()
    if not phone:
        return render_template('errors/404.html')
    views = 1 if not phone.views else phone.views + 1
    Phone.query.filter_by(id=phone.id).update({'views': views})
    db.session.commit()
    price_queries = PhoneShop.query.filter_by(phone_id=phone_id).all()
    prices = []
    for query in price_queries:
        shop = Shop.query.filter_by(id=query.shop_id).first()
        if not query.price:
            continue
        price = str(round(query.price))
        price = price[:len(price) - 3] + ' ' + price[-3:]
        shop_name = shop.name
        url = shop.phones_path + query.external_id
        prices.append([shop_name, price, url])
    if not prices:
        prices = [[], [], []]
    return render_template('main/specs.html', phone=phone, prices=prices, page_title=phone.name)


@blueprint.route('/about')
def about():
    return render_template('main/about.html')

webapp/user/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user, logout_user
from werkzeug.urls import url_parse

from models import db, User, user_phone, Phone
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.main.views import get_prices

blueprint = Blueprint('user', __name__)


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not (user and user.check_password(form.password.data)):
            flash('Неверное имя или пароль.', category='danger')
            return redirect(url_for('user.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('main.index')
        flash('Вы успешно вошли на сайт', category='success')
        return redirect(next_page)
    return render_template('user/login.html', form=form, title='Вход')


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User()
        user.username = form.username.data
        user.email = form.email.data
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Вы успешно зарегистрировались!', category='success')
        return redirect(url_for('user.login'))
    return render_template('user/register.html', title='Регистрация', form=form)


@blueprint.route('/favorites', methods=['GET', 'POST'])
def favorites():
    if not current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user_id = User.query.filter_by(username=current_user.username).first().id
    phone_id = request.args.get('phone_id')
    action = request.args.get('action')
    if Phone.query.filter_by(id=phone_id).count():
        if action == 'del':
            if db.session.query(user_phone).filter_by(phone_id=phone_id, user_id=user_id).count():
                db.engine.execute(f'DELETE FROM user_phone WHERE user_id = {user_id} AND phone_id = {phone_id}')
            return redirect(url_for('user.favorites'))
        elif action == 'add':
            result = db.engine.execute(f'SELECT user_id, phone_id FROM user_phone WHERE user_id = {user_id} AND phone_id = {phone_id}')
            if len(list(result)) == 0:
                db.engine.execute(f'INSERT INTO user_phone VALUES ({user_id}, {phone_id})')
                flash('Добавлено в избранные.', category='primary')
            else:
                flash('Этот товар уже в избранных.', category='danger')
            return redirect(url_for('main.index'))
    user_phone_queries = db.session.query(user_phone).filter_by(user_id=user_id).all()
    phone_ids = [phone_id for _, phone_id in user_phone_queries]
    phones = [Phone.query.filter_by(id=phone_id).first() for phone_id in phone_ids]
    return render_template('user/favorites.html', title='Избранное', phones=get_prices(phones))


@blueprint.route('/login_test')
def login_test():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not (user and user.check_password(form.password.data)):
            flash('Неверное имя или пароль.', category='danger')
            return redirect(url_for('user.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('main.index')
        flash('Вы успешно вошли на сайт', category='success')
        return redirect(next_page)
    return render_template('user/login/login.html', form=form, title='Вход')

webapp/templates/user/favorites.html
{% extends 'base.html' %}

{% block content %}
{% if not phones %}
    Список избранных пуст.
{% else %}

    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Название</th>
            <th scope="col">Цена, ₽</th>
        </tr>
        </thead>
        <tbody>
        {% for phone in phones %}
        <tr>
            <td style="max-width:20px;">
                <div align="center">
                    <img height="60" src="static/{{phone.name.replace('/', '')}} 1.jpg" alt="">
                </div>
            </td>
            <td align="" style="width:800px;padding-left:50px;vertical-align:middle;">
                <p>
                    <a style="font-size:16px;" href="{{ url_for('main.show_specs', phone_id=phone.id) }}"> {{ phone.name
                        }} </a>
                </p>
                <p>
                    <a style="font-size:11px;" href="{{ url_for('main.show_specs', phone_id=phone.id) }}">
                        <i>
                            Экран {{ phone.screen_size }}"
                            {% if phone.ram %}
                            , {{ phone.ram }} оперативной памяти
                            {% endif %}
                            {% if phone.main_cam_resolution %}
                            , камера {{ phone.main_cam_resolution }}
                            {% endif %}
                        </i>
                    </a>
                </p>
            </td>
            <td style="vertical-align:middle;font-size:15px;">
                {% if phones[phone] %}
                {% set ph = phones[phone]|string %}
                <strong>{{ ph[:ph|length - 3] + ' ' + ph[-3:] }}</strong>
                {% endif %}
            </td>
            {% if current_user.is_authenticated %}
            <td style="vertical-align:middle;"><a href="{{ url_for('user.favorites', phone_id=phone.id, action='del') }}">Удалить</a>
            </td>
            {% endif %}
        </tr>

        {% endfor %}
        </tbody>
    </table>
{% endif %}

{% endblock %}

webapp/templates/user/login.html
{% extends 'base.html' %}
{% block content %}
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
				<form class="login100-form validate-form" method="post" action="">
					{{ form.hidden_tag() }}
					<span class="login100-form-title p-b-33">
						Вход
					</span>

					<div class="wrap-input100 validate-input">

						{{ form.username() }}
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="wrap-input100 rs1 validate-input">
						{{ form.password() }}
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="container-login100-form-btn m-t-20">
						{{ form.submit() }}
					</div>

					<div class="text-center p-t-45 p-b-4">
						<span class="txt1">
							Нет аккаунта?
						</span>

						<a href="{{ url_for('user.register') }}" class="txt2 hov1">
							Зарегистрироваться
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	

	
<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

</body>
{% endblock %}

webapp/templates/user/register.html
{% extends 'base.html' %}


{% block content%}
<div class="container-login100">
    <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
        <h2>Регистрация</h2>
        <hr>
        <br>
        <form class="login100-form validate-form" method="post">
            {{ form.hidden_tag() }}
            <div class="text-left p-t-30 p-b-4">
                {{ form.username.label }}
                {{ form.username() }}
                {% for error in form.username.errors %}
                {% endfor %}
            </div>

            <div class="text-left p-t-30 p-b-4">
                {{ form.email.label }}
                {{ form.email() }}

                {% for error in form.email.errors %}
                {% endfor %}
            </div>
            <div class="text-left p-t-30 p-b-4">
                {{ form.password.label }}
                {{ form.password() }}
                {% for error in form.password.errors %}
                {% endfor %}
            </div>
            <div class="text-left p-t-30 p-b-4">
                {{ form.password2.label }}
                {{ form.password2() }}
                {% for error in form.password2.errors %}
                {% endfor %}
            </div>
            <br>
            <div class="container-login100-form-btn m-t-50">{{ form.submit() }}</div>
        </form>
    </div>
</div>
{% endblock %}