webapp/main/views.py
from flask import Blueprint, render_template, request, url_for
from fuzzywuzzy import fuzz

from models import db, Phone, PhoneShop, Shop, normalize_name
from webapp.config import ITEMS_PER_PAGE

blueprint = Blueprint('main', __name__)


@blueprint.route('/')
@blueprint.route('/index')
def index():
    title = 'Смартфоны'
    text = request.args.get('search')
    how = request.args.get('how')
    nothing_found = True

    if text:
        if how == 'pop':
            all_phones = Phone.query.order_by(Phone.views).all()
        else:
            all_phones = Phone.query.all()
        phones = []
        for phone in all_phones:
            ratio1 = fuzz.partial_ratio(normalize_name(phone.name), text)
            ratio2 = fuzz.token_set_ratio(normalize_name(phone.name), text)
            if ratio1 + ratio2 == 200:
                phones = [phone]
                break
            if ratio1 + ratio2 > 150:
                phones.append([phone, ratio1 + ratio2])
        if len(phones) > 1:
            phones = [i[0] for i in sorted(phones, key=lambda x: x[1], reverse=True)]
        if phones:
            nothing_found = False
        return render_template('main/index.html', page_title=title, phones=get_prices(phones),
                               nothing_found=nothing_found)

    nothing_found = False
    page = request.args.get('page', 1, type=int)
    if how == 'pop':
        phones = Phone.query.order_by(Phone.views.desc()).paginate(page, ITEMS_PER_PAGE, False)
    elif how == 'price':
        phones = db.session.query(PhoneShop.phone_id, db.func.min(PhoneShop.price).label('min_price')) \
            .group_by(PhoneShop.phone_id, PhoneShop.price).order_by(PhoneShop.price.desc()) \
            .paginate(page, ITEMS_PER_PAGE, False)
    else:
        phones = Phone.query.paginate(page, ITEMS_PER_PAGE, False)
    next_url = url_for('main.index', page=phones.next_num) if phones.has_next else None
    prev_url = url_for('main.index', page=phones.prev_num) if phones.has_prev else None
    if how == 'price':
        phones_price_sorted = {}
        for item in phones.items:
            phones_price_sorted[Phone.query.filter_by(id=item.phone_id).first()] = round(item.min_price)
        phones = phones_price_sorted
    else:
        phones = get_prices(phones.items)

    return render_template('main/index.html', page_title=title, phones=phones,
                           nothing_found=nothing_found, next_url=next_url, prev_url=prev_url, how=how)


def get_prices(phones):
    """ Функция формирует словарь {телефон: минимальная_цена} для последующего вывода в шаблоне"""

    out = {}
    for phone in phones:
        prices = [round(shop.price) for shop in phone.shops if shop.price]
        out[phone] = str(min(prices)) if prices else None
    return out


@blueprint.route('/specs')
def show_specs():
    phone_id = request.args.get('phone_id', None)
    phone = Phone.query.filter_by(id=phone_id).first()
    if not phone:
        return render_template('errors/404.html')
    views = 1 if not phone.views else phone.views + 1
    Phone.query.filter_by(id=phone.id).update({'views': views})
    db.session.commit()
    price_queries = PhoneShop.query.filter_by(phone_id=phone_id).all()
    prices = []
    for query in price_queries:
        shop = Shop.query.filter_by(id=query.shop_id).first()
        if not query.price:
            continue
        price = str(round(query.price))
        price = price[:len(price) - 3] + ' ' + price[-3:]
        shop_name = shop.name
        url = shop.phones_path + query.external_id
        prices.append([shop_name, price, url])
    if not prices:
        prices = [[], [], []]
    return render_template('main/specs.html', phone=phone, prices=prices, page_title=phone.name)


@blueprint.route('/about')
def about():
    return render_template('main/about.html')

webapp/user/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user, logout_user
from werkzeug.urls import url_parse

from models import db, User, user_phone, Phone
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.main.views import get_prices

blueprint = Blueprint('user', __name__)


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not (user and user.check_password(form.password.data)):
            flash('Неверное имя или пароль.', category='danger')
            return redirect(url_for('user.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('main.index')
        flash('Вы успешно вошли на сайт', category='success')
        return redirect(next_page)
    return render_template('user/login.html', form=form, title='Вход')


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User()
        user.username = form.username.data
        user.email = form.email.data
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Вы успешно зарегистрировались!', category='success')
        return redirect(url_for('user.login'))
    return render_template('user/register.html', title='Регистрация', form=form)


@blueprint.route('/favorites', methods=['GET', 'POST'])
def favorites():
    if not current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user_id = User.query.filter_by(username=current_user.username).first().id
    phone_id = request.args.get('phone_id')
    action = request.args.get('action')
    if Phone.query.filter_by(id=phone_id).count():
        if action == 'del':
            if db.session.query(user_phone).filter_by(phone_id=phone_id, user_id=user_id).count():
                db.engine.execute(f'DELETE FROM user_phone WHERE user_id = {user_id} AND phone_id = {phone_id}')
            return redirect(url_for('user.favorites'))
        elif action == 'add':
            result = db.engine.execute(f'SELECT user_id, phone_id FROM user_phone WHERE user_id = {user_id} AND phone_id = {phone_id}')
            if len(list(result)) == 0:
                db.engine.execute(f'INSERT INTO user_phone VALUES ({user_id}, {phone_id})')
                flash('Добавлено в избранные.', category='primary')
            else:
                flash('Этот товар уже в избранных.', category='danger')
            return redirect(url_for('main.index'))
    user_phone_queries = db.session.query(user_phone).filter_by(user_id=user_id).all()
    phone_ids = [phone_id for _, phone_id in user_phone_queries]
    phones = [Phone.query.filter_by(id=phone_id).first() for phone_id in phone_ids]
    return render_template('user/favorites.html', title='Избранное', phones=get_prices(phones))


@blueprint.route('/login_test')
def login_test():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not (user and user.check_password(form.password.data)):
            flash('Неверное имя или пароль.', category='danger')
            return redirect(url_for('user.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('main.index')
        flash('Вы успешно вошли на сайт', category='success')
        return redirect(next_page)
    return render_template('user/login/login.html', form=form, title='Вход')

webapp/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://i.gyazo.com/d1fca822d77d47c7e18b41f96c9c6810.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/">
    <link href="signin.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="static/css/util.css">
    <link rel="stylesheet" type="text/css" href="static/css/main.css">

    <!--    	<link rel="icon" type="image/png" href="static/images/icons/favicon.ico"/>-->
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="static/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="static/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="static/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="static/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="static/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="static/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="static/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="static/css/util.css">
    <link rel="stylesheet" type="text/css" href="static/css/main.css">
    <!--===============================================================================================-->
    <title>{{ page_title }}</title>
</head>
<body>
<div class="container">

        {% include 'menu.html' %}

        <h2>{{ page_title }}</h2>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <ul>
            {% for category, message in messages %}
            <li>
                <div class="alert alert-{{ category }}" role="alert">
                    {{ message }}
                </div>
            </li>
            {% endfor %}
        </ul>
        {% endif%}
        {% endwith %}
        {% block content %}{% endblock %}
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
                integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
                integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
                integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
                crossorigin="anonymous"></script>
        <script src="js/main.js"></script>
    </div>
</body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-sm navbar-dark bg-primary rounded-bottom">
  <a class="navbar-brand" href="{{ url_for('main.index') }}"><h3>SF</h3></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% if current_user.is_anonymous %}
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('user.login') }}">Войти</a>
        </li>
      <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('user.register') }}">Регистрация</a>
        </li>
      {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
        </li>
      {% endif %}
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('main.about') }}">О проекте</a>
        </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      {% include 'main/search.html' %}
    </form>
  </div>
</nav>
<br>

webapp/templates/slider.html
<style>
    .carousel-control-next,
    .carousel-control-prev {
        filter: invert(50%);
    }
</style>
<div style="padding-left:150px;padding-right:150px;padding-top:100px;padding-bottom:50px;">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
    <div class="carousel-inner" align="center">
        <div class="carousel-item active">
            <img class="d-block w-20" src="static/{{phone.name.replace('/', '')}} 1.jpg" alt="First slide" style="height:600px;">
        </div>
        <div class="carousel-item">
            <img class="d-block w-20" src="static/{{phone.name.replace('/', '')}} 2.jpg" alt="Second slide" style="height:600px;">
        </div>
        <div class="carousel-item">
            <img class="d-block w-20" src="static/{{phone.name.replace('/', '')}} 3.jpg" alt="Third slide" style="height:600px;">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    </div>
</div>